# Generated by Django 6.0.6 on 2026-07-07 19:42

import django.db.models.deletion
import merchants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(default=merchants.models.generate_invoice_uuid, editable=False, max_length=20)),
                ('stock_id', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('merchant_id', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('total', models.CharField(blank=True, default='0', max_length=100, null=True)),
                ('debit', models.CharField(blank=True, default='0', max_length=100, null=True)),
                ('credit', models.CharField(blank=True, default='0', max_length=100, null=True)),
                ('balance', models.CharField(blank=True, default='0', max_length=100, null=True)),
                ('date', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('payment_method', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('payment_reference', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('payment_to', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('source_type', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('stock_handler', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('stock_location', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('stock_source', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=255, null=True)),
                ('rate', models.CharField(blank=True, default='0', max_length=100, null=True)),
                ('quantity', models.CharField(blank=True, default='0', max_length=100, null=True)),
                ('amount', models.CharField(blank=True, default='0', max_length=100, null=True)),
                ('product_code', models.CharField(blank=True, help_text='Real product/template code to view full product details.', max_length=100, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='merchants.invoice')),
            ],
        ),
    ]
