# Generated by Django 5.2.4 on 2025-07-18 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_id', models.CharField(default='generate_cat_uuid', editable=False, max_length=20)),
                ('stock_id', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(blank=True, max_length=100, null=True)),
                ('field_type', models.CharField(blank=True, max_length=100, null=True)),
                ('is_required', models.CharField(blank=True, max_length=255, null=True)),
                ('default_value', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_id', models.CharField(default='generate_stock_uuid', editable=False, max_length=20)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('total_products', models.CharField(blank=True, default='00', max_length=100, null=True)),
                ('invested', models.CharField(blank=True, default='00', max_length=100, null=True)),
                ('sold_product', models.CharField(blank=True, default='00', max_length=100, null=True)),
                ('sale_price', models.CharField(blank=True, default='00', max_length=100, null=True)),
                ('details', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('subcat_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='dashboard.category')),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, default='product', max_length=50, null=True)),
                ('tem_id', models.CharField(default='generate_tem_uuid', editable=False, max_length=20)),
                ('template_name', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('totalbalance', models.CharField(blank=True, default='00', max_length=100, null=True)),
                ('keyvalue', models.CharField(blank=True, max_length=100, null=True)),
                ('keyvalue_required', models.CharField(blank=True, max_length=100, null=True)),
                ('total_category', models.CharField(blank=True, default='00', max_length=100, null=True)),
                ('total_subcategory', models.CharField(blank=True, default='00', max_length=100, null=True)),
                ('total_stock', models.CharField(blank=True, default='00', max_length=100, null=True)),
                ('total_product', models.CharField(blank=True, default='00', max_length=100, null=True)),
                ('sold_product', models.CharField(blank=True, default='00', max_length=100, null=True)),
                ('sold_product_price', models.CharField(blank=True, default='00', max_length=100, null=True)),
                ('prod_id', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('base_price', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True)),
                ('tags', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.category')),
                ('custom_fields', models.ManyToManyField(blank=True, to='dashboard.customfield')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.subcategory')),
            ],
        ),
    ]
