# Generated by Django 5.2.4 on 2025-07-18 21:36

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_id',
            field=models.CharField(default=dashboard.models.generate_cat_uuid, editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_id',
            field=models.CharField(default=dashboard.models.generate_stock_uuid, editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='template',
            name='tem_id',
            field=models.CharField(default=dashboard.models.generate_tem_uuid, editable=False, max_length=20),
        ),
    ]
