# Generated by Django 5.2.4 on 2025-07-18 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_category_cat_id_alter_stock_stock_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='stock_id',
        ),
    ]
