# Generated by Django 5.2.4 on 2025-07-18 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_category_stock_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to='category/'),
        ),
    ]
