# Generated by Django 5.2.4 on 2025-07-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_remove_category_slug_remove_subcategory_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='base_price_percentage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='template',
            name='base_price_percentage_sign',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='template',
            name='base_price_pre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='template',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to='products/'),
        ),
    ]
