# Generated by Django 5.2.4 on 2025-07-23 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_customfield_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customfield',
            name='img',
        ),
    ]
