# Generated by Django 5.2.4 on 2025-07-23 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_remove_customfield_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='category',
        ),
        migrations.RemoveField(
            model_name='template',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='template',
            name='category',
            field=models.ManyToManyField(blank=True, to='dashboard.category'),
        ),
        migrations.AddField(
            model_name='template',
            name='subcategory',
            field=models.ManyToManyField(blank=True, to='dashboard.subcategory'),
        ),
    ]
