# Generated by Django 5.2.4 on 2025-07-23 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_remove_template_category_remove_template_subcategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='slug',
        ),
    ]
