# Generated by Django 5.2.4 on 2025-07-24 00:06

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_alter_template_prod_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
