# Generated by Django 5.2.4 on 2025-08-21 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_alter_template_template_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvancedFilterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filters', models.JSONField(default=dict)),
            ],
        ),
    ]
