# Generated by Django 5.2.4 on 2025-12-28 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_category_tem_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='sold_product_price',
        ),
        migrations.RemoveField(
            model_name='template',
            name='total_stock',
        ),
    ]
