# Generated by Django 5.2.4 on 2025-07-18 21:36

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='mtb_id',
            field=models.CharField(default=accounts.models.generate_mtb_uuid, editable=False, max_length=20),
        ),
    ]
