# Generated by Django 5.2.4 on 2025-08-30 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_mtb_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_pic',
            field=models.FileField(blank=True, null=True, upload_to='accounts/'),
        ),
    ]
