# Generated by Django 5.2.4 on 2025-09-24 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='total_balance',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
