# Generated by Django 5.2.4 on 2025-10-02 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_status_customuser_total_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='total_orders',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
