# Generated by Django 5.2.4 on 2025-10-02 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_total_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='salary',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
