# Generated by Django 5.2.4 on 2025-11-10 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='total_balance',
        ),
        migrations.AddField(
            model_name='customuser',
            name='merchant_balance',
            field=models.CharField(blank=True, default='0', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='merchant_credit',
            field=models.CharField(blank=True, default='0', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='merchant_debit',
            field=models.CharField(blank=True, default='0', max_length=100, null=True),
        ),
    ]
