# Generated by Django 5.2.4 on 2025-11-19 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_customuser_total_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='merchant_address',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
    ]
