# Generated by Django 5.2.4 on 2025-11-22 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_customuser_merchant_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='merchant_credit',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='merchant_debit',
        ),
    ]
