# Generated by Django 5.2.4 on 2025-11-23 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_customuser_merchant_credit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='merchant_address',
            new_name='address',
        ),
    ]
