# Generated by Django 5.2.4 on 2025-12-14 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_rename_merchant_address_customuser_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cnic',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
