# Generated by Django 5.2.4 on 2026-01-11 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_customuser_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='client_balance',
            field=models.CharField(blank=True, default='0', max_length=100, null=True),
        ),
    ]
