# Generated by Django 5.2.4 on 2025-07-18 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_category_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
