# Generated by Django 5.2.4 on 2025-07-23 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_template_base_price_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfield',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to='products/'),
        ),
    ]
