# Generated by Django 5.2.4 on 2025-07-23 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_remove_template_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='available_product',
            field=models.CharField(blank=True, default='00', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='template',
            name='stock_product',
            field=models.CharField(blank=True, default='00', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='sold_product',
            field=models.CharField(blank=True, default='00', max_length=50, null=True),
        ),
    ]
