# Generated by Django 5.2.4 on 2025-07-23 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_template_available_product_template_stock_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.stock'),
        ),
    ]
