# Generated by Django 5.2.4 on 2025-07-23 23:06

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_template_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='prod_id',
            field=models.CharField(blank=True, default=dashboard.models.generate_prod_uuid, max_length=100, null=True),
        ),
    ]
