# Generated by Django 5.2.4 on 2025-07-24 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_alter_template_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
