# Generated by Django 5.2.4 on 2025-07-24 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_alter_template_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='template_name',
            field=models.CharField(blank=True, default='noname', max_length=100, null=True),
        ),
    ]
