# Generated by Django 5.2.4 on 2025-12-14 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_advancedfiltersettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mtb_id', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('read', 'Read'), ('sent', 'Sent'), ('awaiting', 'Awaiting')], default='awaiting', max_length=20)),
                ('text', models.TextField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('expiration_datetime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-datetime'],
            },
        ),
    ]
