# Generated by Django 5.2.4 on 2025-12-14 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_alert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='mtb_id',
            field=models.CharField(max_length=255),
        ),
    ]
