# Generated by Django 5.2.4 on 2025-12-26 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_alter_alert_mtb_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='tem_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
