# Generated by Django 5.2.4 on 2025-12-28 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_remove_template_sold_product_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='sale_price',
            new_name='mtb_id',
        ),
    ]
