# Generated by Django 6.0 on 2025-12-30 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_rename_sale_price_stock_mtb_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='show_price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
