# Generated by Django 5.2.4 on 2026-01-11 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_draftinvoice_draftinvoiceitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftinvoice',
            name='date',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='draftinvoice',
            name='payment_method',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='draftinvoice',
            name='payment_reference',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
